<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bpmndi" nsURI="http://www.omg.org/spec/BPMN/20100524/DI"
    nsPrefix="bpmndi">
  <eClassifiers xsi:type="ecore:EClass" name="BPMNDiagram" eSuperTypes="DI.ecore#//Diagram">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="BPMNDiagram"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
  
    <eStructuralFeatures xsi:type="ecore:EReference" name="plane" ordered="false"
        lowerBound="1" eType="#//BPMNPlane" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="BPMNPlane"/>
        <details key="namespace" value="http://www.omg.org/spec/BPMN/20100524/DI"/>
      </eAnnotations>
    </eStructuralFeatures>


    <eStructuralFeatures xsi:type="ecore:EReference" name="labelStyle" ordered="false"
        upperBound="-1" eType="#//BPMNLabelStyle" containment="true"/>
  </eClassifiers>
  
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEdge" eSuperTypes="DI.ecore#//LabeledEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" ordered="false"
        eType="#//BPMNLabel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bpmnElement" ordered="false"
        eType="ecore:EClass BPMN2.ecore#//BaseElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageVisibleKind" ordered="false"
        eType="#//MessageVisibleKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceElement" ordered="false"
        eType="ecore:EClass DI.ecore#//DiagramElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElement" ordered="false"
        eType="ecore:EClass DI.ecore#//DiagramElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNLabel" eSuperTypes="DI.ecore#//Label">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelStyle" ordered="false"
        eType="#//BPMNLabelStyle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNLabelStyle" eSuperTypes="DI.ecore#//Style">
    <eStructuralFeatures xsi:type="ecore:EReference" name="font" ordered="false" lowerBound="1"
        eType="ecore:EClass DC.ecore#//Font" containment="true"/>
  </eClassifiers>
  
 
  
  <eClassifiers xsi:type="ecore:EClass" name="BPMNPlane" eSuperTypes="DI.ecore#//Plane">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="BPMNPlane"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bpmnElement" ordered="false"
        eType="ecore:EClass BPMN2.ecore#//BaseElement">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="bpmnElement"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>  

  
  <eClassifiers xsi:type="ecore:EClass" name="BPMNShape" eSuperTypes="DI.ecore#//LabeledShape">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" ordered="false"
        eType="#//BPMNLabel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bpmnElement" ordered="false"
        eType="ecore:EClass BPMN2.ecore#//BaseElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="choreographyActivityShape"
        ordered="false" eType="#//BPMNShape"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isExpanded" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHorizontal" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMarkerVisible" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMessageVisible" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="participantBandKind" ordered="false"
        eType="#//ParticipantBandKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageVisibleKind">
    <eLiterals name="initiating"/>
    <eLiterals name="non_initiating" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParticipantBandKind">
    <eLiterals name="top_initiating"/>
    <eLiterals name="middle_initiating" value="1"/>
    <eLiterals name="bottom_initiating" value="2"/>
    <eLiterals name="top_non_initiating" value="3"/>
    <eLiterals name="middle_non_initiating" value="4"/>
    <eLiterals name="bottom_non_initiating" value="5"/>
  </eClassifiers>
</ecore:EPackage>
