<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bpmngraph" nsURI="http://www.imixs.org/bpmn/glsp/graph" nsPrefix="bpmngraph">
  <eClassifiers xsi:type="ecore:EClass" name="BaseElement" eSuperTypes="glsp-graph.ecore#//GNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElement" eSuperTypes="#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskNode" eSuperTypes="#//FlowElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="GatewayNode" eSuperTypes="#//FlowElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventNode" eSuperTypes="#//FlowElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pool" eSuperTypes="#//BaseElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Icon" eSuperTypes="glsp-graph.ecore#//GCompartment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol" eSuperTypes="glsp-graph.ecore#//GCompartment"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow" eSuperTypes="glsp-graph.ecore#//GEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultFlow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
